trigger:
  branches:
    include:
    - '*'
  tags:
    exclude:
    - '*'

variables:
  CKBClientVersion: v0.39.0

jobs:
  - job: IntegrationTest
    timeoutInMinutes: 0
    pool:
      vmImage: 'windows-2019'
    steps:
      - template: devtools/azure/windows-dependencies.yml
        parameters:
          rustup_toolchain: '1.46.0-x86_64-pc-windows-msvc'
      - pwsh: devtools/windows/make CKB_TEST_SEC_COEFFICIENT=5 CKB_TEST_ARGS="-c 4 --no-report" integration
        displayName: Run integration tests
        env:
          CI: true
          SENTRY_DSN: 'https://0e6fe236fbd84432a8df0aed2c3cd7f1@sentry.nervos.org/5'
          LOGBAK_USER: $(LOGBAK_USER)
          LOGBAK_PASSWORD: $(LOGBAK_PASSWORD)
          LOGBAK_SERVER: $(LOGBAK_SERVER)
