[package]
name = "ckb-verification"
version = "0.39.2"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "The CKB verification"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-types = { path = "../util/types", version = "= 0.39.2" }
ckb-store = { path = "../store", version = "= 0.39.2" }
ckb-script = { path = "../script", version = "= 0.39.2" }
ckb-pow = { path = "../pow", version = "= 0.39.2" }
faketime = "0.2.0"
rayon = "1.0"
lru = "0.6.0"
ckb-traits = { path = "../traits", version = "= 0.39.2" }
ckb-chain-spec = { path = "../spec", version = "= 0.39.2" }
ckb-dao = { path = "../util/dao", version = "= 0.39.2" }
ckb-dao-utils = { path = "../util/dao/utils", version = "= 0.39.2" }
ckb-logger = {path = "../util/logger", version = "= 0.39.2"}
ckb-reward-calculator= { path = "../util/reward-calculator", version = "= 0.39.2" }
ckb-error = { path = "../error", version = "= 0.39.2" }
derive_more = { version = "0.99.0", default-features=false, features = ["display"] }
tokio = { version = "0.2", features = ["sync", "blocking", "rt-threaded"] }
ckb-async-runtime = { path = "../util/runtime", version = "= 0.39.2" }

[dev-dependencies]
ckb-chain = { path = "../chain", version = "= 0.39.2" }
ckb-shared = { path = "../shared", version = "= 0.39.2" }
ckb-test-chain-utils = { path = "../util/test-chain-utils", version = "= 0.39.2" }
ckb-resource = { path = "../resource", version = "= 0.39.2" }
rand = "0.6"
