[package]
name = "ckb-snapshot"
version = "0.39.2"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "The ckb rocksdb snapshot wrapper"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-types = { path = "../types", version = "= 0.39.2" }
ckb-chain-spec = { path = "../../spec", version = "= 0.39.2" }
ckb-store = { path = "../../store", version = "= 0.39.2" }
ckb-db = { path = "../../db", version = "= 0.39.2" }
ckb-traits = { path = "../../traits", version = "= 0.39.2" }
ckb-error = { path = "../../error", version = "= 0.39.2" }
ckb-proposal-table = { path = "../proposal-table", version = "= 0.39.2" }
arc-swap = "0.4"
ckb-reward-calculator = { path = "../reward-calculator", version = "= 0.39.2" }
ckb-db-schema = { path = "../../db-schema", version = "= 0.39.2" }
