[package]
name = "ckb-dao-utils"
version = "0.39.2"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "TODO(doc): @keroro520 crate description"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
byteorder = "1.3.1"
ckb-types = { path = "../../types", version = "= 0.39.2" }
ckb-error = { path = "../../../error", version = "= 0.39.2" }
