[package]
name = "ckb-db"
version = "0.39.2"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "TODO(doc): @quake crate description"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-app-config = { path = "../util/app-config", version = "= 0.39.2" }
ckb-logger = { path = "../util/logger", version = "= 0.39.2" }
ckb-error = { path = "../error", version = "= 0.39.2" }
tempfile = "3.0"
libc = "0.2"
rocksdb = { package = "ckb-rocksdb", version = "=0.14.1", features = ["snappy"] }
ckb-db-schema = { path = "../db-schema", version = "= 0.39.2" }
