[package]
name = "ckb-sync"
version = "0.39.2"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "The ckb sync/relayer protocols implementation"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-chain = { path = "../chain", version = "= 0.39.2" }
ckb-shared = { path = "../shared", version = "= 0.39.2" }
ckb-store = { path = "../store", version = "= 0.39.2" }
ckb-db = { path = "../db", version = "= 0.39.2" }
ckb-app-config = {path = "../util/app-config", version = "= 0.39.2"}
ckb-types = {path = "../util/types", version = "= 0.39.2"}
ckb-network = { path = "../network", version = "= 0.39.2" }
ckb-logger = {path = "../util/logger", version = "= 0.39.2"}
ckb-metrics = {path = "../util/metrics", version = "= 0.39.2"}
ckb-util = { path = "../util", version = "= 0.39.2" }
faketime = "0.2.0"
bitflags = "1.0"
ckb-verification = { path = "../verification", version = "= 0.39.2" }
ckb-chain-spec = { path = "../spec", version = "= 0.39.2" }
ckb-channel = { path = "../util/channel", version = "= 0.39.2" }
ckb-traits = { path = "../traits", version = "= 0.39.2" }
lru = "0.6.0"
sentry = { version = "0.17.0", optional = true }
futures = "0.3"
ckb-error = {path = "../error", version = "= 0.39.2"}
ckb-tx-pool = { path = "../tx-pool", version = "= 0.39.2" }
ckb-fee-estimator = { path = "../util/fee-estimator", version = "= 0.39.2" }
governor = "0.3.1"
tempfile = "3.0"

[dev-dependencies]
ckb-test-chain-utils = { path = "../util/test-chain-utils", version = "= 0.39.2" }
rand = "0.6"
ckb-dao = { path = "../util/dao", version = "= 0.39.2" }
ckb-dao-utils = { path = "../util/dao/utils", version = "= 0.39.2" }

[features]
default = []
stats = []
with_sentry = ["sentry"]
