[package]
name = "ckb-multisig"
version = "0.39.2"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "CKB multi-signature library."
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-error = { path = "../../error", version = "= 0.39.2" }
ckb-logger = { path = "../logger", version = "= 0.39.2" }
ckb-crypto = { path = "../crypto", version = "= 0.39.2" }

[dev-dependencies]
rand = "0.6.5"
