[package]
name = "ckb-error"
version = "0.39.2"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "TODO(doc): @keroro520 crate description"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
thiserror = "1.0.22"
anyhow = "1.0.34"
ckb-occupied-capacity = { path = "../util/occupied-capacity", version = "= 0.39.2" }
derive_more = { version = "0.99.0", default-features = false, features = ["display"] }
