[package]
name = "ckb-app-config"
version = "0.39.1"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"
description = "TODO(doc): @doitian crate description"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
clap = { version = "2" }
serde = { version = "1.0", features = ["derive"] }
serde_plain = "0.3.0"
toml = "0.5"
path-clean = "0.1.0"
ckb-logger = { path = "../../util/logger", version = "= 0.39.1" }
ckb-logger-config = { path = "../../util/logger-config", version = "= 0.39.1" }
ckb-metrics-config = { path = "../../util/metrics-config", version = "= 0.39.1" }
ckb-chain-spec = {path = "../../spec", version = "= 0.39.1"}
ckb-jsonrpc-types = {path = "../jsonrpc-types", version = "= 0.39.1"}
ckb-pow = { path = "../../pow", version = "= 0.39.1" }
ckb-resource = { path = "../../resource", version = "= 0.39.1"}
ckb-build-info = { path = "../build-info", version = "= 0.39.1" }
ckb-types = { path = "../types", version = "= 0.39.1" }
ckb-fee-estimator = { path = "../fee-estimator", version = "= 0.39.1" }
secio = { version="0.4.3", features = ["molc"], package="tentacle-secio" }
multiaddr = { version="0.2.0", package="tentacle-multiaddr" }
rand = "0.6"
sentry = { version = "0.17.0", optional = true }

[features]
with_sentry = ["sentry"]

[dev-dependencies]
tempfile = "3.0"
